stages:
  - publish

.kaniko:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: publish
  variables:
    SUFFIX: ""
  before_script:
    - mkdir -p /kaniko/.docker
    # yamllint disable-line rule:line-length
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n ${DOCKER_HUB_REGISTRY_USER}:${DOCKER_HUB_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context ./
      --cache=true
      --use-new-run
      --dockerfile $CI_COMMIT_TAG/Dockerfile
      --destination $DOCKER_HUB_REGISTRY_IMAGE:$DOCKER_HUB_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG

DHub:Prod:
  extends:
    - .kaniko
  variables:
    DOCKER_HUB_COMMIT_TAG: ${CI_COMMIT_TAG}
